---
agents:
  - REPO: "apm-agent-dotnet"
    FEATURES_PATH: "test/Elastic.Apm.Feature.Tests/Features"
  - REPO: "apm-agent-go"
    FEATURES_PATH: "features"
  - REPO: "apm-agent-java"
    FEATURES_PATH: "apm-agent-core/src/test/resources/specs"
    JSON_SPECS_PATH: "apm-agent-core/src/test/resources/json-specs"
  - REPO: "apm-agent-python"
    FEATURES_PATH: "tests/bdd/features"
  - REPO: "apm-agent-ruby"
    FEATURES_PATH: "features"
