---
agents:
  - REPO: "apm-agent-dotnet"
    FEATURES_PATH: "test/Elastic.Apm.Feature.Tests/Features"
  - REPO: "apm-agent-go"
    FEATURES_PATH: "features"
    JSON_SPECS_PATH: "internal/testdata/json-specs"
  - REPO: "apm-agent-java"
    FEATURES_PATH: "apm-agent-core/src/test/resources/specs/cucumber"
    JSON_SPECS_PATH: "apm-agent-core/src/test/resources/json-specs"
  - REPO: "apm-agent-php"
    FEATURES_PATH: "tests/APM_Agents_shared/gherkin-specs"
    JSON_SPECS_PATH: "tests/APM_Agents_shared/json-specs"
  - REPO: "apm-agent-python"
    FEATURES_PATH: "tests/bdd/features"
    JSON_SPECS_PATH: "tests/upstream/json-specs"
  - REPO: "apm-agent-ruby"
    FEATURES_PATH: "features"
    JSON_SPECS_PATH: "spec/fixtures"
  - REPO: "apm-agent-nodejs"
    JSON_SPECS_PATH: "test/fixtures/json-specs"
