// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

@Library('apm@current') _

pipeline {
  agent { label 'linux && immutable' }
  environment {
    REPO = 'apm'
    BASE_DIR = "src/github.com/elastic/${env.REPO}"
    HOME = "${env.WORKSPACE}"
    NOTIFY_TO = credentials('notify-to')
    JOB_GCS_BUCKET = credentials('gcs-bucket')
    JOB_GIT_CREDENTIALS = "f6c7695a-671e-4f4f-a331-acdce44ff9ba"
    PATH = "${env.PATH}:${env.WORKSPACE}/bin"
    PIPELINE_LOG_LEVEL='INFO'
  }
  options {
    timeout(time: 3, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
  }
  parameters {
    booleanParam(name: 'DRY_RUN_MODE', defaultValue: false, description: 'If true, allows to execute this pipeline in dry run mode, without sending a PR.')
    booleanParam(name: 'FORCE_SEND_PR', defaultValue: false, description: 'If true, will force sending a PR.')
  }
  stages {
    stage('Checkout'){
      steps {
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}",
          branch: "master",
          repo: "git@github.com:elastic/${REPO}.git",
          credentialsId: "${JOB_GIT_CREDENTIALS}"
        )
        script {
          dir("${BASE_DIR}"){
            def regexps =[
              "^tests/agents/gherkin-specs/.*"
            ]
            env.GHERKIN_SPECS_UPDATED = isGitRegionMatch(
              from: "${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}",
              to: "${env.GIT_COMMIT}",
              patterns: regexps)

            // regexp for JSON specs
            regexps =[
              "^tests/agents/json-specs/.*"
            ]
            env.JSON_SPECS_UPDATED = isGitRegionMatch(
              from: "${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}",
              to: "${env.GIT_COMMIT}",
              patterns: regexps)
          }
        }
        stash allowEmpty: true, name: 'source', useDefaultExcludes: false
      }
    }
    stage('Send Pull Request for BDD specs'){
      options {
        warnError('Pull Requests to APM agents failed')
      }
      when {
        beforeAgent true
        anyOf {
          expression { return env.GHERKIN_SPECS_UPDATED != "false" }
          expression { return params.FORCE_SEND_PR == "true" }
        }
      }
      steps {
        deleteDir()
        unstash 'source'
        dir("${BASE_DIR}"){
          script {
            def agents = readYaml(file: '.ci/.jenkins-agents.yml')
            def parallelTasks = [:]
            agents['agents'].each { agent ->
              parallelTasks["apm-agent-${agent.NAME}"] = generateStepForAgent(repo: "${agent.REPO}", filesType: "gherkin", filesPath: "${agent.FEATURES_PATH}")
            }

            parallel(parallelTasks)
          }
        }
      }
    }
    stage('Send Pull Request for JSON specs'){
      options {
        warnError('Pull Requests to APM agents failed')
      }
      when {
        beforeAgent true
        anyOf {
          expression { return env.JSON_SPECS_UPDATED != "false" }
          expression { return params.FORCE_SEND_PR == "true" }
        }
      }
      steps {
        deleteDir()
        unstash 'source'
        dir("${BASE_DIR}"){
          script {
            def agents = readYaml(file: '.ci/.jenkins-agents.yml')
            def parallelTasks = [:]
            agents['agents'].each { agent ->
              parallelTasks["apm-agent-${agent.NAME}"] = generateStepForAgent(repo: "${agent.REPO}", filesType: "json", filesPath: "${agent.JSON_SPECS_PATH}")
            }

            parallel(parallelTasks)
          }
        }
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult()
    }
  }
}

def generateStepForAgent(Map params = [:]){
  def repo = params.containsKey('repo') ? params.get('repo') : error('generateStepForAgent: repo argument is required')
  def filesType = params.containsKey('filesType') ? params.get('filesType') : error('generateStepForAgent: filesType argument is required. Valid values: [gherkin | json]')
  def filesPath = params.containsKey('filesPath') ? params.get('filesPath') : error('generateStepForAgent: filesPath argument is required')
  return {
    node('linux && immutable') {
      catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
        deleteDir()
        unstash 'source'
        dir("${BASE_DIR}"){
          setupAPMGitEmail(global: true)
          sh script: """.ci/scripts/prepare-spec-changes.sh "${repo}" "${filesType}" "${filesPath}" """, label: "Prepare ${filesType} changes for ${repo}"
          dir(".ci/${repo}") {
            if (params.DRY_RUN_MODE) {
              echo "DRY-RUN: ${repo}"
            } else {
              githubCreatePullRequest(title: "test: synchronizing ${filesType} spec", labels: 'automation')
            }
          }
        }
      }
    }
  }
}
