@startuml kafka_consume
hide footbox
participant "Application (Consumer)" as app
participant "APM agent" as apm
queue       Kafka as queue

activate app
loop while true
    activate apm #00BFB3 
    apm -> apm: transaction.End()  
    
    app -> queue: **consumer.Consume()**
    deactivate apm
    deactivate app
    activate queue

    group Message processing flow
        ... ~~blocking operation~~ ...
        queue --> app: message
        
        deactivate queue
        activate app
        activate apm #00BFB3
        apm -> apm: transaction.Start()
    end

    deactivate app
    deactivate apm
end
@enduml