name: "APM Agents meta issue handler"
on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  meta-issue-handler:
    runs-on: ubuntu-latest
    steps:
    - name: Check team membership for user
      uses: elastic/get-user-teams-membership@1.1.0
      id: checkUserMember
      with:
        username: ${{ github.actor }}
        team: 'apm'
        usernamesToExclude: |
          apmmachine
        GITHUB_TOKEN: ${{ secrets.APM_TECH_USER_TOKEN }}
    - name: Create sub issues
      if: steps.checkUserMember.outputs.isTeamMember == 'true' && contains(github.event.issue.labels.*.name, 'meta') && contains(github.event.issue.labels.*.name, 'apm-agents')
      uses: elastic/gh-action-meta-subissues-creator@1.0.2
      id: create_sub_issues
      with:
        token: "${{ secrets.APM_TECH_USER_TOKEN }}"
        metaIssue: "${{ toJSON(github.event.issue) }}"
        bodyRegex: "(.*)(<!---repos-start--->.*<!---repos-end--->)(.*)"
        labelsToExclude: "meta,apm-agents"
        specLabels: "spec-poc,apm-agents"
